### ISSUE TITLE
npm install appear error

### ISSUE THREAD

**Issue by akira32** [tony-xlh/Ionic-Vue-QR-Code-Scanner#1]
I want to find the barcode scanner plugin for ionic+vue3+typescript. This example is very relative to my need.
I use Visual Studo Code open the folder from zip. I input npm install appear the errors as below:
Could someone know how to solve those problems?

MacBook-Air Ionic-Vue-QR-Code-Scanner-main % npm install
npm warn old lockfile
npm warn old lockfile The package-lock.json file was created with an old version of npm,
npm warn old lockfile so supplemental metadata must be fetched from the registry.
npm warn old lockfile
npm warn old lockfile This is a one-time fix-up, please be patient...
npm warn old lockfile
npm warn old lockfile Could not fetch metadata for @vue/vue-loader-v15@15.9.8 HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/@vue%2fvue-loader-v15 - Not found
npm warn old lockfile     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15
npm warn old lockfile     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm warn old lockfile     at async RegistryFetcher.packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:90:19)
npm warn old lockfile     at async RegistryFetcher.manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:128:23)
npm warn old lockfile     at async /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:712:24 {
npm warn old lockfile   headers: [Object: null prototype] {
npm warn old lockfile     date: [ 'Thu, 08 Aug 2024 06:59:46 GMT' ],
npm warn old lockfile     'content-type': [ 'application/json' ],
npm warn old lockfile     'content-length': [ '21' ],
npm warn old lockfile     connection: [ 'keep-alive' ],
npm warn old lockfile     vary: [ 'Accept-Encoding' ],
npm warn old lockfile     server: [ 'cloudflare' ],
npm warn old lockfile     'cf-ray': [ '8afda021a85f6a80-TPE' ],
npm warn old lockfile     'x-fetch-attempts': [ '1' ],
npm warn old lockfile     'x-local-cache-status': [ 'skip' ]
npm warn old lockfile   },
npm warn old lockfile   statusCode: 404,
npm warn old lockfile   code: 'E404',
npm warn old lockfile   method: 'GET',
npm warn old lockfile   uri: 'https://registry.npmjs.org/@vue%2fvue-loader-v15',
npm warn old lockfile   body: { error: 'Not found' },
npm warn old lockfile   pkgid: '@vue/vue-loader-v15@15.9.8'
npm warn old lockfile }
npm warn old lockfile Could not fetch metadata for @typescript-eslint/visitor-keys@5.28.0 FetchError: Invalid response body while trying to fetch https://registry.npmjs.org/@typescript-eslint%2fvisitor-keys: aborted
npm warn old lockfile     at /usr/local/lib/node_modules/npm/node_modules/minipass-fetch/lib/body.js:170:15
npm warn old lockfile     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm warn old lockfile     at async Response.json (/usr/local/lib/node_modules/npm/node_modules/minipass-fetch/lib/body.js:75:17)
npm warn old lockfile     at async RegistryFetcher.packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:98:25)
npm warn old lockfile     at async RegistryFetcher.manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:128:23)
npm warn old lockfile     at async /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:712:24 {
npm warn old lockfile   code: 'ECONNRESET',
npm warn old lockfile   errno: 'ECONNRESET',
npm warn old lockfile   type: 'system'
npm warn old lockfile }
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: '@achrinza/node-ipc@9.2.5',
npm warn EBADENGINE   required: {
npm warn EBADENGINE     node: '8 || 9 || 10 || 11 || 12 || 13 || 14 || 15 || 16 || 17 || 18'
npm warn EBADENGINE   },
npm warn EBADENGINE   current: { node: 'v20.14.0', npm: '10.8.1' }
npm warn EBADENGINE }
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
npm warn deprecated consolidate@0.15.1: Please upgrade to consolidate v1.0.0+ as it has been modernized with several long-awaited fixes implemented. Maintenance is supported by Forward Email at https://forwardemail.net ; follow/watch https://github.com/ladjs/consolidate for updates and release changelog
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated domexception@2.0.1: Use your platform's native DOMException instead
npm warn deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm warn deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm warn deprecated webpack-chain@6.5.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm warn deprecated core-js@3.23.1: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm warn deprecated @humanwhocodes/object-schema@1.2.1: Use @eslint/object-schema instead
npm warn deprecated @humanwhocodes/config-array@0.9.5: Use @eslint/config-array instead
npm warn deprecated @babel/plugin-proposal-private-methods@7.17.12: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-methods instead.
npm warn deprecated @babel/plugin-proposal-optional-chaining@7.17.12: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
npm warn deprecated @babel/plugin-proposal-private-property-in-object@7.17.12: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-property-in-object instead.
npm warn deprecated @babel/plugin-proposal-optional-catch-binding@7.16.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
npm warn deprecated @babel/plugin-proposal-json-strings@7.17.12: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-json-strings instead.
npm warn deprecated @babel/plugin-proposal-numeric-separator@7.16.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
npm warn deprecated @babel/plugin-proposal-dynamic-import@7.16.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-dynamic-import instead.
npm warn deprecated @babel/plugin-proposal-unicode-property-regex@7.17.12: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-unicode-property-regex instead.
npm warn deprecated @babel/plugin-proposal-class-static-block@7.18.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-static-block instead.
npm warn deprecated @babel/plugin-proposal-object-rest-spread@7.18.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
npm warn deprecated @babel/plugin-proposal-async-generator-functions@7.17.12: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
npm warn deprecated @babel/plugin-proposal-class-properties@7.17.12: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm warn deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.17.12: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm warn deprecated @babel/plugin-proposal-logical-assignment-operators@7.17.12: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-logical-assignment-operators instead.
npm warn deprecated @babel/plugin-proposal-export-namespace-from@7.17.12: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-export-namespace-from instead.
npm error code ECONNRESET
npm error syscall read
npm error errno -54
npm error network read ECONNRESET
npm error network This is a problem related to network connectivity.
npm error network In most cases you are behind a proxy or have bad network settings.
npm error network
npm error network If you are behind a proxy, please make sure that the
npm error network 'proxy' config is set properly.  See: 'npm help config'
npm error A complete log of this run can be found in: /Users/akira/.npm/_logs/2024-08-08T06_58_22_689Z-debug-0.log

**Comment by akira32** [comment]
I run npm install second time. I found the problem as below:

npm warn old lockfile Could not fetch metadata for @vue/vue-loader-v15@15.9.8 HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/@vue%2fvue-loader-v15 - Not found
npm warn old lockfile     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15
npm warn old lockfile     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm warn old lockfile     at async RegistryFetcher.packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:90:19)
npm warn old lockfile     at async RegistryFetcher.manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:128:23)
npm warn old lockfile     at async /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:712:24 {
npm warn old lockfile   headers: [Object: null prototype] {
npm warn old lockfile     date: [ 'Thu, 08 Aug 2024 07:23:28 GMT' ],
npm warn old lockfile     'content-type': [ 'application/json' ],
npm warn old lockfile     'content-length': [ '21' ],
npm warn old lockfile     connection: [ 'keep-alive' ],
npm warn old lockfile     vary: [ 'Accept-Encoding' ],
npm warn old lockfile     server: [ 'cloudflare' ],
npm warn old lockfile     'cf-ray': [ '8afdc2d88c6b8285-TPE' ],
npm warn old lockfile     'x-fetch-attempts': [ '1' ],
npm warn old lockfile     'x-local-cache-status': [ 'skip' ]
npm warn old lockfile   },
npm warn old lockfile   statusCode: 404,
npm warn old lockfile   code: 'E404',
npm warn old lockfile   method: 'GET',
npm warn old lockfile   uri: 'https://registry.npmjs.org/@vue%2fvue-loader-v15',
npm warn old lockfile   body: { error: 'Not found' },
npm warn old lockfile   pkgid: '@vue/vue-loader-v15@15.9.8'
npm warn old lockfile }
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: '@achrinza/node-ipc@9.2.5',
npm warn EBADENGINE   required: {
npm warn EBADENGINE     node: '8 || 9 || 10 || 11 || 12 || 13 || 14 || 15 || 16 || 17 || 18'
npm warn EBADENGINE   },
npm warn EBADENGINE   current: { node: 'v20.14.0', npm: '10.8.1' }
npm warn EBADENGINE }
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.

**Comment by xulihang** [comment]
This is a warning. You can just ignore this.
